name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: shogo82148/actions-setup-perl@v1.17.0

      - run: ./ci/scripts/sorter.perl README.md > README.md
      
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main