name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1.17.0

      - name: Sort Markdown with Perl
        run: |
            perl -ne 'if(/^#{1,3}/){$current=$_;}elsif(! /^\s*$/){push( @{$entries{$current}},"$_\n");}END{for $chapter (sort keys %entries){print $chapter;print sort @{$entries{$chapter}};}}' README.md > README.md.bak
            rm -f README.md
            mv README.md.bak README.md
      
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main